### ISSUE TITLE
Exam 2 Q10

### ISSUE THREAD

**Issue by hanusspi** [Kusko25/ids-ws-23-rwth_Exam_Prep#1]
You have a misscalculation in your formula for b. For the new centroid you divide by alpha * w_i + wb (the number of elements of the batch for the new cluster)

**Comment by Kusko25** [comment]
I had noticed a mistake there, but I thought it was
```
    new_c1 = (sum(cluster1)*len(cluster1)+alpha*w_c1*c1)/(len(cluster1)+(alpha*w_c1))
    new_c2 = (sum(cluster2)*len(cluster2)+alpha*w_c2*c2)/(len(cluster2)+(alpha*w_c2))
```
That I mulitplied by len(clusterX) here which I shouldn't have done. (And fixed since)
But the division already looks like what you wrote. So what do you mean?

**Comment by hanusspi** [comment]
Sorry, youre partially right. The error i saw was wrong, at least partially. First of all you use sum(cluster1), which should be the average of vector of all the new points per cluster. So you should divide that sum by the number of new points for each cluster. In my point of view that boils down to just taking the sum of vectors. I can only assume that he put it in the lectures as he did to improve readability. Than you get (0,2) as a result.

**Comment by Kusko25** [comment]
Yeah, I tried to do it with more detail to be closer to the lecture slides, but with no points in the second cluster that meant a divide by zero error and frankly, I couldn't be bothered.
Thanks for the feedback though it's good to see some people taking an interest in the notebooks
